version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "53:66:66:90:2e:ee:0c:91:2f:b4:a2:db:97:62:9b:e0"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sudo ~/deploy-me.sh"
 
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
